# Generated by Django 3.2.9 on 2022-06-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Award', '0003_rating'),
    ]

    operations = [
    ]
