# Generated by Django 3.2.9 on 2022-06-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Award', '0005_auto_20220612_2337'),
    ]

    operations = [
    ]
